### PR TITLE
#42 added sitemaps to magazinearticles, magazineissue. and added .git…

### LINKED ISSUE #42: Add sitemap for Magazine content
In order to improve search engine indexing, we can publish a sitemap.

## Task
Create a sitemap for the Magazine Articles and Magazine Issues.

### PR DESCRIPTION
**Pull request by dhelbegor**
Closes #42 
Added a custom get_sitemaps_url to the MagazineArticle and MagazineIssue.

In additional i've added the .gitignore file.

### CODE REVIEW

**Comment by brylie** [comment]
Please mention the issue this is closing, using GitHub [issue linking markdown](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by brylie** [comment]
Thanks for contributing this feature so quickly :-)



Please mention the issue this is closing, using GitHub [issue linking markdown](https://help.github.com/articles/closing-issues-using-keywords/). You can add the 'Closes #' to the PR description.

**Comment by dhelbegor** [comment]
Sry about the delay, I can hel even more :D, in the next days I'll see in what more I can help

**Comment by brylie** [comment]
@dhelbegor thank you for your contribution :-) @marycklein and I have reviewed the code and our contribution process, and are grateful to you for your work here.

**Pull request merged**
