### PR TITLE
Issue #659

### LINKED ISSUE #659: (FLK-D200) One-line docstring should fit on one line with quotes
## Description
If a docstring fits in a single line (72 characters according to PEP8), it is recommended to have the quotes on the same line.

## Occurrences
There are 13 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/FLK-D200/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/FLK-D200/occurrences/)

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
Closes #659

Hi, I try to help on #659 . Please review

### CODE REVIEW

**Review by brylie — CHANGES_REQUESTED** [review]
This looks good. However, docstrings usually use triple quotes. Please use triple quotes for all of the changed docstrings

**Comment by viktoriussuwandi** [comment]
no problem, already used triple quotes for all of the changed docstrings.

**Review by brylie — CHANGES_REQUESTED** [review]
This is a subtle problem, but the issue is related to having newlines in the comments:

> If a docstring fits in a single line (72 characters according to PEP8), it is recommended to have the quotes on the same line.

So, we still want to use triple quotes, but make sure to remove newlines, e.g.,

Bad
```py
"""
There is a new line above this sentence.
"""
```
Good
```py
"""There is not a new line before this sentence."""
```

So, the change would look something like this:

```diff
- """
- Docstring comment
- """
+ """Docstring comment"""
```

**Comment by viktoriussuwandi** [comment]
Exactly, I found that case on [donations/models.py](https://github.com/WesternFriend/WF-website/pull/672/commits/a378d9ea52949e3a1d9864004aee4ac87b481acc) and [accounts/managers.py](https://github.com/WesternFriend/WF-website/pull/672/commits/f2b4287858f0e7906deeece595dd7b683d787227), and already try to fixed it. Please Re-review again. Sorry for late submission by the way.

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
@all-contributors please add @viktoriussuwandi for code

**Comment by brylie** [comment]
@all-contributors please add @viktoriussuwandi for docs

**Pull request merged**
