### PR TITLE
added tests for accounts app

### PR DESCRIPTION
**Pull request by alhcomer**
Added user manager and user model tests. This is my first ever pull request so apologies if it's not right :)

### CODE REVIEW

**Review by brylie — CHANGES_REQUESTED** [review]

**Comment by brylie** [comment]
Thanks for this contribution!  Just one small idea for improvement :-)

**Comment by alhcomer** [comment]
SonarCloud is flagging security issues due to using a password variable in the TestClass despite it not being sensitive. Any advice for getting around this?

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
We can ignore the SonarCloud analysis.

**Comment by brylie** [comment]
@all-contributors please add @alhcomer for code, tests

**Pull request merged**
